## 21.12.30

# 예외처리
### 예외의 개념
- 예외의 개념
  + 에러 : 프로그램으로 처리할 수 없기 때문에 에러 발생 시 프로그램이 중단됨 | ex) 네트워크 작업 처리 시 랜선이 끊어짐
  + 예외 : 프로그램 실행 중에 발생할 수 있는 가벼운 사건 | 프로그래머가 충분히 예측할 수 있는 사건 | 프로그램적으로 얼마든지 처리할 수 있는 오류
  + 자바에서 예외가 발생하는 경우
    * 정수를 0으로 나누는 경우
    * 배열의 인덱스가 음수 값을 가지거나 배열의 길이를 넘어서는 경우
    * 부적절한 형변환이 발생하는 경우
    * 입출력 시 인터럽트(interrupt)가 발생하는 경우
    * 입출력을 위해 필요한 파일이 존재하지 않는 경우
  + 자바는 객체지향 언어이므로 예외도 객체로 처리함
    * 예외를 객체로 처리하기 위해 객체를 생성할 클래스가 필요함
  + 발생 가능성이 있는 모든 예외 사항을 미리 예측하여 다양한 예외 클래스를 제공함
  + 예외가 발생하면 자바가상머신이 던진(throw) 예외 객체를 받아서 (catch) 예외 처리 프로그램을 수행하고 프로그램을 계속 진행함
  + 프로그램에 예외 처리 로직을 구현하지 않은 경우
    * 기본 예외 처리 핸들러 : 에러 메시지를 화면에 출력하고, 실행을 중지시키는 역할
- 예외 클래스
  + 자바는 예외 객체를 생성하기 위한 다양한 예외 클래스가 존재함
  + 모든 예외는 java.lang.Throwable 클래스의 자식 클래스인 java.lang.Exception 클래스의 자식 클래스로 만들어짐
  + java.lang.Error : 처리할 수 없는 치명적인 에러 처리 =====================>
  + java.lang.Exception : 정상적인 프로그램 동작 시 만날 수 있는 오류 처리 ===> 두 클래스 위에 java.lang.Throwable
  + java.lang.RuntimeException의 하위 클래스 들은 예외 처리를 포함하지 않아도 컴파일이 되는 예외 클래스들이다.
    * 실행 시에 발생되는 예외이므로 프로그램이 예외를 다루는 소스코드를 포함하지 않아도 컴파일러가 컴파일을 해줌
    * 위 클래스가 아닌 예외 클래스는 예외 처리 로직이 없으면 컴파일이 되지 않음
  + RuntimeException의 자식 클래스들만 이해하면 나머지 예외 클래스들은 프로그램 실행전에 미리 예외 처리 로직을 추가할 수 있게 됨
  + 이름만으로 어떤 의미의 예외인지 알 수 있도록 작성됨
    * ArithmeticException : 정수를 0으로 나누는 경우 산술 연산 오류
    * IndexOutofBoundsException : 배열의 인덱스가 배열의 길이를 넘어서면 발생하는 오류
    * IllegalArgumentException : 매서드의 매개변수 유형을 잘못 사용하면 발생하는 오류
    * IOException : 입출력 시에 지정한 파일이 시스템에 존재하지 않으면 발생하는 오류
### 예외처리 
- 예외처리
  + 예외 처리 기능은 자바 언어를 더욱 강하게(robust) 만드는 요인임
  + 예외가 발생한 매서드 내에서 직접 처리하는 방식
    * try-catch 구문
    * 다중 catch 구문
    * 상속을 이용한 예외 처리
    * finally 블록
  + 해당 매서드를 호출한 곳으로 예외 처리를 넘기는 방식
    * throws 예약어
- try-catch 구문
  + 예외가 발생한 매서드 내에서 직접 처리하는 방법 중의 하나임
  ```java
  try{
    예외 발생 가능이 있는 소스코드;
  }catch(예외 타입 매개변수명){
    예외타입의 예외가 발생할 경우 수행될 소스코드;
  }
  ```
  + try 블록
    * 프로그래머가 프로그램 중에서 예외가 발생할 수 있는 소스코드들을 try 블록 안에 작성함
    * try 블록은 최소한 하나의 catch 블록이 있어야함
  + catch 블록
    * try 블록 다음에 위치함
    * catch 블록의 매개변수는 예외 객체가 발생했을 때 참조하는 변수명으로, 반드시 java.lang.Throwable 클래스의 하위 클래스 타입으로 선언
  + 지정한 타입의 예외 객체 발생 -> try블록의 나머지 문장들은 수행 X -> JVM은 발생한 예외 객체를 발생시킴 -> 발생한 예외 객체 타입에 해당하는 catch 블록을 수행
- 다중 catch 구문
  + 프로그램에서 발생하는 예외에 따라서 적절하게 예외 처리를 분기시켜야 함
  + 다중 catch 블록을 사용하여 여러 개의 예외를 처리함
  ```java
  try{
    int num1 = Integer.parseInt(args[0]);
    int num2 = Integer.parseInt(args[1]);
    int num3 = num1 / num2
  } catch (ArithmeticException e){
        "정수를 0으로 나눌 수 없습니다";
  } catch (ArrayIndexOutOfBoundsException e){
        "명령행 매개변수 2개가 필요합니다";
  } catch (NumberFormatException e){
        "매개변수는 정수만 허용합니다.";
  }
  ```
- 상속을 이용한 예외 처리
  + 자바에서 지원하는 모든 예외 클래스는 Exception 클래스의 자식 클래스로 존재함
  + Exception 객체 : 형변환에 의해 Exception 타입의 변수로 할당
  ```java
  Exception ex = new ArithmeticException();
  ex = new ArrayIndexOutOfBoundsException(); 
  ```
  + 다만 단일 catch 블록으로 사용시 구체적으로 어떤 예외가 발생했는지를 알 수 없음
  + 따라서 다중 catch 구문을 사용하고 마지막 catch 블록에 Exception 타입을 집어넣는다.
- finally 블록
  + try블록 내의 문장에서 예외가 발생하지 않을 경우 : try 블록은 수행되지만 catch 블록은 수행되지 않음
  + try블록 내의 문장에서 예외가 발생한 경우 : try 블록은 수행되지 않지만 해당 예외 객체의 타입과 같은 매개변수를 지정한 catch 블록은 수행됨
  + finally 블록은 try-catch블록 지정 시 try 블록과 함께 사용될 수 있음
  + 필수적으로 사용하는 블록은 아니므로 프로그래머의 편의에 따라 사용함
  + finally 블록이 사용되면 그 블록의 내용은 예외 발생 유무나 예외 catch 유무와 상관 없이 무조건 수행됨
  + 데이터베이스 연동 로직, 파일 입출력 로직을 수행한 후에 반드시 수행되어야 할 로직이 있는 경우에 사용함
  + 마지막 catch 다음에 catch와 같은 모양으로 사용함
- throws 예약어
  + 자바의 예외 처리는 예외가 발생한 지점에서 try-catch 또는 try-catch-finally 블록을 이용하여 예외 처리 로직을 작성함
  + 예외가 발생한 매서드를 호출한 지점으로 예외를 전달하여 처리하는 방법 : throws 예약어
  + 여러 개의 예외 클래스 이름을 나열할 수 있음
  + throws를 사용하여 예외 처리를 다른 매서드로 전달할 때, 발생된 예외 객체가 RuntimeException의 자식 클래스인 경우에는 명시적으로 throws 문을 사용하지 않아도 자동으로 throws 됨
  + 굳이 throws를 하는 이유는 개인-서버1-서버2 같은 형태일 때 서버2에서 예외가 발생하면 서버2에서 직접 처리하는 것이 아니라 개인에게 예외 메시지를 출력해야하기 때문
# 사용자 정의 예외
### 사용자 정의 예외 처리
- 사용자 예외 클래스의 정의
  + 프로그램에서 예외 발생 시
    * API에서 제공 : 해당 예외 클래스를 이용하여 예외 처리 로직 구현
    * API에서 제공 X : 개발자가 직접 예외 클래스를 정의해서 사용
  +  모든 예외 클래스의 최상위 클래스인 java.lang.Exception 클래스를 상속받아 정의함
  +  class 예외 클래스 명 extends Exception
  ```java
  class BadBankingException extends Exception{
      public BadBankingException(String s){
          super(s);
      }
  }
  ```
- throw 예약어
  + 자바 가상 머신은 프로그램 수행 중 예외가 발생하면 자동으로 해당하는 예외 객체를 발생시킨 후 catch 블록을 수행함
  + 프로그램에서 직접 예외를 생성했으면 throw new 예외클래스명(); 으로 설정해줘야 한다.
  + throw를 이용한 예외 발생시에도 try-catch 구문을 이용하여 예외 처리를 해야함
  + 사용자 정의 예외 클래스 형태의 예외 객체는 자바 가상 머신에 의해 자동으로 발생되지 않음
    * 사용자 정의 예외 클래스 객체를 발생시켜서 처리하려면 반드시 throw 예약어를 이용해야함
  ```java
  class Account{
	public void withdraw(int money) throws BadBanking  {
		if(money < 0) {
			throw new BadBanking("error");
		}
		System.out.println("good");
	  }
  }
  ```
 












